
ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS woovi_subaccount_id TEXT NULL,
  ADD COLUMN IF NOT EXISTS pix_split_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS commission_type TEXT NOT NULL DEFAULT 'percentage',
  ADD COLUMN IF NOT EXISTS commission_value NUMERIC NOT NULL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS commission_fixed NUMERIC NOT NULL DEFAULT 0;
